/**
 * Welten-Essenz-Skilltree: Koordinaten in viewBox 0..200 (weit auseinander, wenig Text in den Kreisen).
 * `labelShort` = 1–2 Wörter; ausführlicher Text in `name` + `effect` (CSS-Hover-Tooltip im UI).
 */

/**
 * @typedef {{
 *   id: string;
 *   name: string;
 *   labelShort: string;
 *   cost: number;
 *   requires: string[];
 *   x: number;
 *   y: number;
 *   path: string;
 *   effect: string;
 *   clickBonus?: number;
 *   passiveBonus?: number;
 *   expeditionSpeedBonus?: number;
 *   ghoulPpsMult?: number;
 *   rareRelicDropBonus?: number;
 *   rasereiEveryTenth?: boolean;
 * }} SkillNodeDef
 */

/** @param {string} id */
export function getSkillNodeById(id) {
  return SKILL_TREE_NODES.find((n) => n.id === id);
}

export const SKILL_TREE_NODES = /** @type {SkillNodeDef[]} */ ([
  {
    id: 'center',
    name: 'Das Erwachen',
    labelShort: 'Erwachen',
    cost: 1,
    requires: [],
    x: 100,
    y: 100,
    path: 'Zentrum',
    effect: 'Schaltet die drei Pfade (Blut, Schatten, Eroberer) frei; ohne diesen Knoten sind keine weiteren Skills kaufbar.',
  },
  // —— Blut
  {
    id: 'blood_1',
    name: 'Puls der Fingerknochen',
    labelShort: 'Puls',
    cost: 3,
    requires: ['center'],
    x: 72,
    y: 92,
    path: 'Blut',
    effect: '+4 % Knochen pro Klick (stapelt additiv).',
    clickBonus: 0.04,
  },
  {
    id: 'blood_2',
    name: 'Ader des Altars',
    labelShort: 'Ader',
    cost: 8,
    requires: ['blood_1'],
    x: 56,
    y: 80,
    path: 'Blut',
    effect: '+6 % Knochen pro Klick.',
    clickBonus: 0.06,
  },
  {
    id: 'blood_3',
    name: 'Herzklopfen der Toten',
    labelShort: 'Herz',
    cost: 18,
    requires: ['blood_2', 'hybrid_bs'],
    x: 40,
    y: 64,
    path: 'Blut',
    effect: '+8 % Knochen pro Klick.',
    clickBonus: 0.08,
  },
  {
    id: 'blood_4',
    name: 'Blutpakt der Sieben',
    labelShort: 'Pakt',
    cost: 40,
    requires: ['blood_3'],
    x: 24,
    y: 48,
    path: 'Blut',
    effect: '+12 % Knochen pro Klick.',
    clickBonus: 0.12,
  },
  {
    id: 'blood_5',
    name: 'Knochen-Bohrer',
    labelShort: 'Bohrer',
    cost: 70,
    requires: ['blood_4'],
    x: 12,
    y: 34,
    path: 'Blut',
    effect: '+50 % Klickstärke (additiv).',
    clickBonus: 0.5,
  },
  {
    id: 'blood_6',
    name: 'Raserei',
    labelShort: 'Raserei',
    cost: 95,
    requires: ['blood_5'],
    x: 8,
    y: 22,
    path: 'Blut',
    effect: 'Jeder 10. Altar-Klick zählt doppelt (Knochen).',
    rasereiEveryTenth: true,
  },
  {
    id: 'blood_7',
    name: 'Blutfontäne',
    labelShort: 'Fontäne',
    cost: 130,
    requires: ['blood_6'],
    x: 16,
    y: 12,
    path: 'Blut',
    effect: '+25 % Knochen pro Klick.',
    clickBonus: 0.25,
  },
  {
    id: 'blood_8',
    name: 'Schlund des Altars',
    labelShort: 'Schlund',
    cost: 200,
    requires: ['blood_7'],
    x: 28,
    y: 6,
    path: 'Blut',
    effect: '+18 % Knochen pro Klick.',
    clickBonus: 0.18,
  },
  // —— Schatten
  {
    id: 'shadow_1',
    name: 'Flüstern der Gruft',
    labelShort: 'Flüstern',
    cost: 3,
    requires: ['center'],
    x: 128,
    y: 92,
    path: 'Schatten',
    effect: '+5 % passives BpS.',
    passiveBonus: 0.05,
  },
  {
    id: 'shadow_2',
    name: 'Nebel der Schichten',
    labelShort: 'Nebel',
    cost: 8,
    requires: ['shadow_1'],
    x: 144,
    y: 80,
    path: 'Schatten',
    effect: '+7 % passives BpS.',
    passiveBonus: 0.07,
  },
  {
    id: 'shadow_3',
    name: 'Schatten-Webwerk',
    labelShort: 'Web',
    cost: 18,
    requires: ['shadow_2', 'hybrid_bs'],
    x: 160,
    y: 64,
    path: 'Schatten',
    effect: '+9 % passives BpS.',
    passiveBonus: 0.09,
  },
  {
    id: 'shadow_4',
    name: 'Kern der Fabrik',
    labelShort: 'Kern',
    cost: 40,
    requires: ['shadow_3'],
    x: 176,
    y: 48,
    path: 'Schatten',
    effect: '+12 % passives BpS.',
    passiveBonus: 0.12,
  },
  {
    id: 'shadow_5',
    name: 'Nekromantische Aura',
    labelShort: 'Aura',
    cost: 70,
    requires: ['shadow_4'],
    x: 186,
    y: 34,
    path: 'Schatten',
    effect: '+10 % passives BpS.',
    passiveBonus: 0.1,
  },
  {
    id: 'shadow_6',
    name: 'Ewige Knechtschaft',
    labelShort: 'Ghule',
    cost: 95,
    requires: ['shadow_5'],
    x: 192,
    y: 22,
    path: 'Schatten',
    effect: 'Ghul-Generatoren produzieren +20 % BpS.',
    ghoulPpsMult: 0.2,
  },
  {
    id: 'shadow_7',
    name: 'Schweigende Hallen',
    labelShort: 'Hallen',
    cost: 130,
    requires: ['shadow_6'],
    x: 182,
    y: 12,
    path: 'Schatten',
    effect: '+8 % passives BpS.',
    passiveBonus: 0.08,
  },
  {
    id: 'shadow_8',
    name: 'Katakomben-Meister',
    labelShort: 'Kata',
    cost: 200,
    requires: ['shadow_7'],
    x: 168,
    y: 6,
    path: 'Schatten',
    effect: '+10 % passives BpS.',
    passiveBonus: 0.1,
  },
  // —— Eroberer
  {
    id: 'war_1',
    name: 'Erster Tritt',
    labelShort: 'Tritt',
    cost: 3,
    requires: ['center'],
    x: 90,
    y: 118,
    path: 'Eroberer',
    effect: '+6 % Plünderungs-Tempo (kürzerer Balken).',
    expeditionSpeedBonus: 0.06,
  },
  {
    id: 'war_2',
    name: 'Banner aus Rippen',
    labelShort: 'Banner',
    cost: 8,
    requires: ['war_1'],
    x: 80,
    y: 136,
    path: 'Eroberer',
    effect: '+8 % Plünderungs-Tempo.',
    expeditionSpeedBonus: 0.08,
  },
  {
    id: 'war_3',
    name: 'Beute-Katalog',
    labelShort: 'Katalog',
    cost: 18,
    requires: ['war_2', 'hybrid_bw'],
    x: 70,
    y: 154,
    path: 'Eroberer',
    effect: '+10 % Plünderungs-Tempo.',
    expeditionSpeedBonus: 0.1,
  },
  {
    id: 'war_4',
    name: 'Heerlager',
    labelShort: 'Lager',
    cost: 40,
    requires: ['war_3'],
    x: 58,
    y: 174,
    path: 'Eroberer',
    effect: '+12 % Plünderungs-Tempo.',
    expeditionSpeedBonus: 0.12,
  },
  {
    id: 'war_5',
    name: 'Pfadfinder',
    labelShort: 'Pfad',
    cost: 70,
    requires: ['war_4'],
    x: 46,
    y: 188,
    path: 'Eroberer',
    effect: 'Expeditionen ~10 % schneller (Balken).',
    expeditionSpeedBonus: 0.11,
  },
  {
    id: 'war_6',
    name: 'Spürsinn',
    labelShort: 'Spür',
    cost: 95,
    requires: ['war_5'],
    x: 100,
    y: 194,
    path: 'Eroberer',
    effect: '+5 % Chance auf selteneres Beute-Relikt & Loot (RNG-Bias).',
    rareRelicDropBonus: 0.05,
  },
  {
    id: 'war_7',
    name: 'Feldherrn-Stiefel',
    labelShort: 'Marsch',
    cost: 130,
    requires: ['war_6'],
    x: 128,
    y: 184,
    path: 'Eroberer',
    effect: '+10 % Plünderungs-Tempo.',
    expeditionSpeedBonus: 0.1,
  },
  {
    id: 'war_8',
    name: 'Kriegsschatten',
    labelShort: 'Krieg',
    cost: 200,
    requires: ['war_7'],
    x: 154,
    y: 172,
    path: 'Eroberer',
    effect: '+12 % Plünderungs-Tempo.',
    expeditionSpeedBonus: 0.12,
  },
  // —— Querverbindungen
  {
    id: 'hybrid_bs',
    name: 'Kreuzung Nebel & Blut',
    labelShort: 'Kreuz',
    cost: 22,
    requires: ['blood_2', 'shadow_2'],
    x: 100,
    y: 60,
    path: 'Verbindung',
    effect: '+3 % Klick & +3 % BpS.',
    clickBonus: 0.03,
    passiveBonus: 0.03,
  },
  {
    id: 'hybrid_bw',
    name: 'Gezackte Triumphe',
    labelShort: 'Trium',
    cost: 22,
    requires: ['blood_2', 'war_2'],
    x: 50,
    y: 108,
    path: 'Verbindung',
    effect: '+5 % Klick & +5 % Expedition.',
    clickBonus: 0.05,
    expeditionSpeedBonus: 0.05,
  },
  {
    id: 'hybrid_sw',
    name: 'Schatten & Feld',
    labelShort: 'Feld',
    cost: 22,
    requires: ['shadow_2', 'war_2'],
    x: 150,
    y: 108,
    path: 'Verbindung',
    effect: '+5 % BpS & +5 % Expedition.',
    passiveBonus: 0.05,
    expeditionSpeedBonus: 0.05,
  },
  {
    id: 'triad_nexus',
    name: 'Dreifaltiger Schlüssel',
    labelShort: 'Nexus',
    cost: 200,
    requires: ['blood_8', 'shadow_8', 'war_8'],
    x: 100,
    y: 148,
    path: 'Nexus',
    effect: '+10 % Klick, BpS & Plünderungs-Tempo.',
    clickBonus: 0.1,
    passiveBonus: 0.1,
    expeditionSpeedBonus: 0.1,
  },
]);

export function getSkillTreeEdges() {
  /** @type {{ from: string; to: string }[]} */
  const edges = [];
  for (const node of SKILL_TREE_NODES) {
    for (const req of node.requires) {
      edges.push({ from: req, to: node.id });
    }
  }
  return edges;
}
